book_keeper/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("finance.urls")),
]

book_keeper/finance/urls.py
from django.urls import path
from . import views

app_name    = "finance"
urlpatterns = [
    path('', views.index, name="index"),
    path('category/', views.category, name="category")
]

book_keeper/finance/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):

    class Meta:
        db_table = "category"

    name    = models.CharField(verbose_name="カテゴリ名",max_length=20)
    income  = models.BooleanField(verbose_name="収入フラグ",default=False)
    
    def __str__(self):
        return self.name


class Balance(models.Model):

    class Meta:
        db_table = "balance"

    dt          = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)
    pay_dt      = models.DateField(verbose_name="決済日")
    category    = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.PROTECT)
    value       = models.IntegerField(verbose_name="金額")

    def __str__(self):
        return self.category.name

book_keeper/finance/forms.py
from django import forms 

from .models import Category,Balance

class BalanceForm(forms.ModelForm):

    class Meta:
        model   = Balance
        fields  = [ "category","pay_dt","value" ]


class CategoryForm(forms.ModelForm):

    class Meta:
        model   = Category
        fields  = [ "name","income" ]

book_keeper/finance/views.py
from django.shortcuts import render,redirect
from django.views import View

from .models import Category,Balance
from .forms import CategoryForm,BalanceForm

import datetime

class IndexView(View):
    
    #日ごとの収支計算し返却する。
    def calc(self, balances):

        today       = ""
        before_day  = ""

        day_balances = []
        dic         = { "day":"","income":0,"spending":0 }

        for balance in balances:
            today   = str(balance.pay_dt.day)

            #前回のループと日付不一致の時、アペンドして新規作成
            if today != before_day:

                #初期状態ではない場合のみアペンド
                if dic["day"] != "":
                    day_balances.append(dic)

                dic         = { "day":"","income":0,"spending":0 }
                dic["day"]  = today

            if balance.category.income:
                dic["income"] += balance.value
            else:
                dic["spending"] += balance.value

            before_day  = today

        day_balances.append(dic)
        print(day_balances)

        return day_balances

    def get(self, request, *args, **kwargs):

        

        context     = {}
        context["categories"]   = Category.objects.all()


        if "year" in request.GET and "month" in request.GET:
            #TODO:指定された年月でBalanceを絞り込む
            return redirect("finance:index")
        else:
            #今月の初日を手に入れる。
            dt  = datetime.datetime.now()
            dt  = dt.replace(day=1)

            #TODO:ここのバランスは全データを抜き取っているため、カレンダーと食い違う。.filter()で当月か指定した月だけ抜き取り
            context["balances"]     = Balance.objects.filter(pay_dt__year=dt.year,pay_dt__month=dt.month).order_by("pay_dt")

        oldest_balance  = Balance.objects.order_by("pay_dt").first()
        newest_balance  = Balance.objects.order_by("-pay_dt").first()

        oldest_pay_dt   = oldest_balance.pay_dt
        newest_pay_dt   = newest_balance.pay_dt

        print(oldest_pay_dt)
        print(newest_pay_dt)



        day_balances    = self.calc(context["balances"])

        #今月を手に入れる
        month       = dt.month

        #month_dateはweek_dateのリスト、week_dateは日付のリスト
        month_date  = []
        week_date   = []

        #最終的に作られるmonth_dateのイメージ。このように複数のweek_dateを含む。月の最初が日曜日ではない場合、必要な数だけ空欄をアペンドしておく
        """
        [ ['  ', '  ', '1 ', '2 ', '3 ', '4 ', '5 '],
          ['6 ', '7 ', '8 ', '9 ', '10', '11', '12'],
          ['13', '14', '15', '16', '17', '18', '19'],
          ['20', '21', '22', '23', '24', '25', '26'],
          ['27', '28', '29', '30']
          ]

          [ {"dt":'6 ',"income":3000,"spending":600 }, '7 ', '8 ', '9 ', '10', '11', '12'],
        """

        #一日ずつずらしてweek_dateにアペンドする。
        #datetimeのオブジェクトは .weekday() で数値化した曜日が出力される(月曜日が0、日曜日が6)

        #日曜日以外の場合、空欄を追加する。
        if dt.weekday() != 6:
            for i in range(dt.weekday()+1):
                week_date.append("")

        #1日ずつ追加して月が変わったらループ終了
        while month == dt.month:
            
            #TODO:ここで辞書型をアペンド(日付、収入の合計、支出の合計)
            dic = {"day":str(dt.day),"income":0,"spending":0 }

            flag    = False
            for day_balance in day_balances:
                if dic["day"] == day_balance["day"]:
                    week_date.append(day_balance)
                    flag    = True
                    break

            if not flag:
                week_date.append(dic)

            #1日追加する
            dt  = dt + datetime.timedelta(days=1)

            #週末になるたびに追加する。
            if dt.weekday() == 6:
                month_date.append(week_date)
                week_date   = []

        #一ヶ月の最終週を追加する。
        if dt.weekday() != 6:
            month_date.append(week_date)

        context["month_date"]   = month_date


        return render(request,"finance/index.html",context)


    def post(self, request, *args, **kwargs):

        form    = BalanceForm(request.POST)

        if form.is_valid():
            print("OK")
            form.save()
        else:
            print("NG")


        return redirect("finance:index")

index   = IndexView.as_view()


class CategoryView(View):

    def post(self, request, *args, **kwargs):

        form    = CategoryForm(request.POST)

        if form.is_valid():
            print("OK")
            form.save()
        else:
            print("NG")

        return redirect("finance:index")

category    = CategoryView.as_view()

book_keeper/templates/finance/callender.html
{% load humanize %}
<!--カレンダー-->
<form action="" method="GET">
    <select name="year">
        <option value=""></option>
    </select>
    <select name="month">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
    </select>
</form>

<table class="calender">
    <thead>
        <tr class="calender_head">
            <td>日</td>
            <td>月</td>
            <td>火</td>
            <td>水</td>
            <td>木</td>
            <td>金</td>
            <td>土</td>
        </tr>
    </thead>
    <tbody>
        {% for week_date in month_date %}
        <tr>
            {% for day in week_date %}
            <td>
                <div>{{ day.day }}</div>
                <div>{{ day.income|default:""|intcomma }}</div>
                <div>{{ day.spending|default:""|intcomma }}</div>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

book_keeper/templates/finance/index.html
{% load static %}
{% load humanize %}


<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>家計簿</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>



    <link rel="stylesheet" href="{% static 'finance/css/style.css' %}">
    <script src="{% static 'finance/js/script.js' %}"></script>

</head>
<body>
    
    <!--ここに家計簿のタイトルを-->

    <div class="row mx-0">
        <div class="col-md-6">{% include "finance/callender.html" %}</div>
        <div class="col-md-6">{% include "finance/list.html" %}</div>
    </div>

    {% comment %}
    <p>カテゴリ追加フォーム</p>
    
    <form action="{% url 'finance:category' %}" method="POST">
        {% csrf_token %}
        <div><input type="text" name="name" placeholder="カテゴリ名"></div>
        <div>収入フラグ<input type="checkbox" name="income"></div>
        <input type="submit" value="送信">
    </form>

    <p>収支入力フォーム</p>

    <form action="" method="POST">
        {% csrf_token %}
        <select name="category">
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="pay_dt" readonly>
        <input type="number" name="value" value="0">
        <input type="submit" value="送信">
    </form>

    <table>
        <tbody>
            {% for balance in balances %}
            <tr>
                <td>{{ balance.dt }}</td>
                <td>{{ balance.pay_dt }}</td>
                <td>{{ balance.category.name }}</td>
                <td>{{ balance.value|intcomma }}円</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endcomment %}


    {% comment %}

    <!--カレンダー-->
    <form action="" method="GET">
        <select name="year">
            <option value=""></option>
        </select>
        <select name="month">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
        </select>
    </form>

    <table class="calender">
        <thead>
            <tr class="calender_head">
                <td>日</td>
                <td>月</td>
                <td>火</td>
                <td>水</td>
                <td>木</td>
                <td>金</td>
                <td>土</td>
            </tr>
        </thead>
        <tbody>
            {% for week_date in month_date %}
            <tr>
                {% for day in week_date %}
                <td>
                    <div>{{ day.day }}</div>
                    <div>{{ day.income|default:""|intcomma }}</div>
                    <div>{{ day.spending|default:""|intcomma }}</div>
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endcomment %}






</body>
</html>

book_keeper/templates/finance/list.html
{% load humanize %}
<p>カテゴリ追加フォーム</p>

<form action="{% url 'finance:category' %}" method="POST">
    {% csrf_token %}
    <div><input type="text" name="name" placeholder="カテゴリ名"></div>
    <div>収入フラグ<input type="checkbox" name="income"></div>
    <input type="submit" value="送信">
</form>

<p>収支入力フォーム</p>

<form action="" method="POST">
    {% csrf_token %}
    <select name="category">
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <input type="text" name="pay_dt" readonly>
    <input type="number" name="value" value="0">
    <input type="submit" value="送信">
</form>

<table>
    <tbody>
        {% for balance in balances %}
        <tr>
            <td>{{ balance.dt }}</td>
            <td>{{ balance.pay_dt }}</td>
            <td>{{ balance.category.name }}</td>
            <td>{{ balance.value|intcomma }}円</td>
        </tr>
        {% endfor %}
    </tbody>
</table>